baseURL = "https://debezium.io/"
languageCode = "en-us"
title = "Debezium"
theme = "debezium"
license = "Apache-2.0"

# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[params]
  font_family = "lato"
  
  # logo is for all page
  logo = "https://debezium.io/images/color_white_debezium_type_600px.svg"

  # logo white is for homepage logo, you can use colorful logo too...
  logo_white = ""
  
  # when logo is empty, it will shown your site title

  # Change default color scheme with a color name or color code.
  primary_color = "#02007e"
  body_color = "#f9f9f9"
  text_color = "#636363"
  text_color_dark = "#242738"
  white_color = "#ffffff"
  light_color = "#f8f9fa"  


  ################## english navigation #################
  [[Languages.en.menu.main]]
  name = "FAQ"
  url = "faq"
  weight = 2

  [[Languages.en.menu.main]]
  name = "DOCUMENTATION"
  url = "documentation"
  weight = 3

  [[Languages.en.menu.main]]
  name = "RELEASES"
  url = "releases"
  weight = 3

  [[Languages.en.menu.main]]
  name = "COMMUNITY"
  url = "community"
  weight = 3

  [[Languages.en.menu.main]]
  name = "BLOG"
  url = "blog"
  weight = 3

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
